name: Configuracion primeros workflows

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  prueba:
    runs-on: Ubuntu-latest
    outputs:
        var: ${{steps.primero.outputs.var}}
    steps:
    - name: Ejecutar echo
      id: primero
      run: |
        echo "var=Hola Mundo Antigup" >> "$GITHUB_ENV"
        echo "var=Hola Mundo Nuevo" >> "$GITHUB_OUTPUT"
    - name: Use var
      env: 
        var2: ${{steps.primero.outputs.var}}
      run: echo "$var2"

  prueba2:
    runs-on: Ubuntu-latest
    needs: prueba
    
    steps:
    - name: Ejecutar de nuevo la var
      run: echo "$var"

    - name: recuperar var
      env:
        name: variable
        url: ${{needs.steps.primero.outputs.var}}
      run: echo "$url"
