name: Configuracion primeros workflows

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  prueba:
    runs-on: Ubuntu:latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
    - name: Ejecutar echo
      run: "echo ${{secrets.DB_NAME}} \n"    
