name: Configuracion primeros workflows

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  prueba:
    runs-on: Ubuntu-latest
    outputs:
        var: ${{steps.primero.outputs.var}}
    steps:
    - name: Ejecutar echo
      id: primero
      run: |
        echo "var=Hola Mundo Antiguo" >> "$GITHUB_ENV"
        echo "var=Hola Mundo Nuevo" >> "$GITHUB_OUTPUT"
        echo "var2=Hola Mundo Nuevo 2" >> "$GITHUB_OUTPUT"
    - name: Use var 
      run: echo "$var"

  prueba2:
    runs-on: Ubuntu-latest
    needs: prueba
    
    steps:
    - name: Ejecutar de nuevo la var
      run: echo "$var2"

    - name: recuperar var
      env:
        name: variable
        run: echo "${{ needs.steps.primero.outputs.var }}"
      
